export interface Card {

    name: string,
    manaCost: string,
    cmc: number,
    colors: any,
    colorIdentity: any,
    type: string,
    supertypes: any,
    types: any,
    subtypes: any,
    rarity: string,
    set: string,
    setName: string,
    text: string,
    artist: string,
    number: string,
    power: string,
    toughness: string,
    layout: string,
    multiverseid: number,
    imageUrl: string,
    variations: any,
    rulings: any,
    foreignNames: any,
    printings: any,
    originalText: string,
    originalType: string,
    legalities: any,
    id: string

}
